# Info about this config. Used for packaging & other purposes.
info:
  name: service-template-node
  version: 0.0.1
  description: A blueprint for MediaWiki REST API services

# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: ncpu

# Logger info
logging:
  level: warn
  streams:
    # Use gelf-stream -> logstash
  - type: gelf
    host: logstash1003.eqiad.wmnet
    port: 12201

# Statsd metrics reporter
metrics:
  type: txstatsd
  host: statsd.eqiad.wmnet
  port: 8125

services:
  - name: service-template-node
    # a relative path or the name of an npm package, if different from name
    module: ./app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 6927
      # interface: localhost # uncomment to only listen on localhost
      # compressionLevel: 3 # output gzip compression level, 6 by default
      # more per-service config settings

      # Graphoid-specific settings
      # List of domains the service is allowed to access (with their subdomains)
      domains:
        - mediawiki.org
        - wikibooks.org
        - wikidata.org
        - wikimedia.org
        - wikimediafoundation.org
        - wikinews.org
        - wikipedia.org
        - wikiquote.org
        - wikisource.org
        - wikiversity.org
        - wikivoyage.org
        - wiktionary.org
      # Additional list of allowed domains with their replacements
      # Even though the subdomains will also be allowed, the substitution
      # will be done only on fully matched hostname.
      # For example, it allows "graph.wmflabs.org" to be replaced with "localhost:12345"
      domainMap: {}
      # Which protocol should service use for protocol-relative URLs like //example.com/path
      defaultProtocol: https
      # Error if it takes longer than this to handle the request
      timeout: 5000
