# Number of worker processes to spawn.
# Set to 0 to run everything in a single process without clustering.
# Use 'ncpu' to run as many workers as there are CPU units
num_workers: 0

# Log error messages and gracefully restart a worker if v8 reports that it
# uses more heap (note: not RSS) than this many mb.
worker_heap_limit_mb: 250

# Logger info
logging:
  level: trace
#  streams:
#  # Use gelf-stream -> logstash
#  - type: gelf
#    host: logstash1003.eqiad.wmnet
#    port: 12201

# Statsd metrics reporter
metrics:
  type: log
  #host: localhost
  #port: 8125

services:
  - name: graphoid
    # a relative path or the name of an npm package, if different from name
    module: ./app.js
    # optionally, a version constraint of the npm package
    # version: ^0.4.0
    # per-service config
    conf:
      port: 6927
      # interface: localhost # uncomment to only listen on localhost
      # more per-service config settings
      # the location of the spec, defaults to spec.yaml if not specified
      # spec: ./spec.template.yaml
      # allow cross-domain requests to the API (default '*')
      cors: '*'
      # to disable use:
      # cors: false
      # to restrict to a particular domain, use:
      # cors: restricted.domain.org
      # URL of the outbound proxy to use (complete with protocol)
      # proxy: http://my.proxy.org:8080
      # the list of domains for which not to use the proxy defined above
      # no_proxy_list:
      #   - domain1.com
      #   - domain2.org
      # Graphoid-specific settings
      # List of domains the service is allowed to access (with their subdomains)
      domains:
        - localhost
        - 127.0.0.1
        - wmflabs.org
        - mediawiki.org
        - wikibooks.org
        - wikidata.org
        - wikimedia.org
        - wikimediafoundation.org
        - wikinews.org
        - wikipedia.org
        - wikiquote.org
        - wikisource.org
        - wikiversity.org
        - wikivoyage.org
        - wiktionary.org
      # Additional list of allowed domains with their replacements
      # Even though the subdomains will also be allowed, the substitution
      # will be done only on fully matched hostname.
      # For example, it allows "graph.wmflabs.org" to be replaced with "localhost:12345"
      domainMap:
        127.0.0.1: localhost:8080

      # Which protocol should service use for protocol-relative URLs like //example.com/path
      defaultProtocol: http
      # Error if it takes longer than this to handle the request
      timeout: -1
